### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by AbiramiRobertKennedy** [bookHubTeam4/bookHub_UI#3]
Design the homepage so that user will be able to search any books without logging in

**Comment by AbiramiRobertKennedy** [comment]
![new mockup 1](https://user-images.githubusercontent.com/29199168/47374012-d7004d00-d6a1-11e8-862a-c980b0b02883.png)

**Comment by elvispeter91** [comment]
![image](https://user-images.githubusercontent.com/22705472/47539326-c9afb200-d89d-11e8-9122-832856c3b44c.png)

Home page implemented
